apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: statusquarkusio-8doq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-abjd-tenant/status-quarkus-io/statusquarkusio-8doq@sha256:8d38b10f0b3444cb6b4c4c09ae75d76b8c74369d40829d05cd6a50d8083a384f
        name: my-java-quarkus
        resources: {}
status: {}
