apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-8doq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-8doq
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-8doq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-8doq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-8doq
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-abjd-tenant/status-quarkus-io/statusquarkusio-8doq@sha256:8d38b10f0b3444cb6b4c4c09ae75d76b8c74369d40829d05cd6a50d8083a384f
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
